"""Pynguin-based automatic test generator."""

import os
import tempfile
import subprocess
import queue
import threading
from typing import Callable, Optional
from .models import TestGenerationResult


class PynguinGenerator:
    """Generates unit tests using Pynguin automatic test generation."""
    
    def __init__(self):
        """Initialize Pynguin generator."""
        os.environ["PYNGUIN_DANGER_AWARE"] = "1"
    
    def generate_tests(self, code: str, log_callback: Optional[Callable[[str], None]] = None) -> TestGenerationResult:
        """Generate unit tests for the given Python code using Pynguin.
        
        Args:
            code: Python source code to generate tests for
            log_callback: Optional callback function to receive log messages during generation
            
        Returns:
            TestGenerationResult containing generated test code or error
        """
        tmp_dir = tempfile.mkdtemp()
        code_file = os.path.join(tmp_dir, "user_code.py")
        output_dir = os.path.join(tmp_dir, "tests")
        os.makedirs(output_dir, exist_ok=True)

        try:
            # Write the code to a temporary file
            with open(code_file, "w", encoding="utf-8") as f:
                f.write(code)

            # Setup environment for subprocess
            env = os.environ.copy()
            env["PYTHONIOENCODING"] = "utf-8"

            # Run Pynguin
            cmd = [
                "pynguin",
                "--project-path", tmp_dir,
                "--output-path", output_dir,
                "--module-name", "user_code",
                "-v"
            ]

            p = subprocess.Popen(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                env=env,
                text=True,
                bufsize=1
            )

            # Stream output
            for line in p.stdout:
                if log_callback:
                    log_callback(line.rstrip("\n"))

            p.wait()

            # Read generated test file
            test_file_path = os.path.join(output_dir, "test_user_code.py")
            if os.path.exists(test_file_path):
                with open(test_file_path, "r", encoding="utf-8") as f:
                    test_code = f.read()
                return TestGenerationResult(test_code=test_code, method='pynguin')
            else:
                return TestGenerationResult(
                    test_code="",
                    error="Test file not generated by Pynguin",
                    method='pynguin'
                )

        except Exception as e:
            return TestGenerationResult(
                test_code="",
                error=f"Error during Pynguin generation: {str(e)}",
                method='pynguin'
            )
    
    def generate_tests_async(self, code: str, task_queue: queue.Queue) -> None:
        """Generate tests asynchronously, putting results in the queue.
        
        Args:
            code: Python source code to generate tests for
            task_queue: Queue to send log messages and results to
        """
        def log_callback(line: str):
            task_queue.put({"type": "log", "line": line})
        
        result = self.generate_tests(code, log_callback)
        
        if result.error:
            task_queue.put({"type": "error", "message": result.error})
        else:
            task_queue.put({"type": "result", "test_code": result.test_code})
